version: '3.0'

services:
  projectnestjs:
    build: ./nestjs/.
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - internalnet

  nginx:
    container_name: nginxcontainer
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web/dist:/usr/share/nginx/html
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge